name: analyze app
on: workflow_dispatch
jobs:
  analyze:
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter pub run custom_lint